### ISSUE TITLE
tango9 branch does not compile on windows

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-cs/pytango#36]
Reported by @NexeyaSGara:

> I have some problems building PyTango on Windows.
>
> I have modified the solution and followed your instructions, but I 
> have a link error with tango lib related to pipes and tango 
> DevVarLongStringArray and DevVarDoubleStringArray.
>
> In device_pipe.cpp
>
>               typedef typename TANGO_const2type(tangoArrayTypeConst)
> TangoArrayType;
>
>               TangoArrayType tmp_arr;
>
> *            //obj >> (&tmp_arr); with this line commented no problem!!!*
If I understood correctly, this line generates a compilation error.
When you comment it, the compilation is fine.
But at runtime it won't work, right?
Could you send me the compilation error? Thanks in advance

>
>               bopy::object data;
>
>               switch (extract_as)
>
>               {
>
>                   default:
>
>                   case PyTango::ExtractAsNumpy:
>
> #                 ifndef DISABLE_PYTANGO_NUMPY
>
>                       data =
> to_py_numpy<tangoArrayTypeConst>(&tmp_arr,
> 1);
>
>                       break;
>
> #                 endif
>
>                   case PyTango::ExtractAsList:
>
>                   case PyTango::ExtractAsPyTango3:
>
>                       data = to_py_list(&tmp_arr);
>
>                       break;
>
>                   case PyTango::ExtractAsTuple:
>
>                       data = to_py_tuple(&tmp_arr);
>
>                       break;
>
>                   case PyTango::ExtractAsString: /// @todo
>
>                   case PyTango::ExtractAsNothing:
>
>                       data = bopy::object();
>
>                       break;
>
>               }
>
>               return data;
>
>           }
>
> Can you help us on that ?
>
> Thanks

**Comment by NexeyaSGara** [comment]
Hi, 
The fix seems ok on my side, no more error on the link (tested only with Visual 2008), but since I had the same errors with the others visual versions, normally, I think we are ok.
