### ISSUE TITLE
Support command options feature in PyTango HL and pogo plugin 

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-cs/pytango#37]
In PyTango HL, `command` decorator should support *display_level* and *polling_period*.
Valid for both PyTango 8 and 9.

**Comment by vxgmichel** [comment]
I can take care of that. Do we need to backport it to pytango8?

**Comment by NexeyaSGara** [comment]
I will do the pogo templates.

**Comment by NexeyaSGara** [comment]
Are we ok with that generation for PyTango HL

    @command(
    display_level=DispLevel.EXPERT,
    )
    @DebugIt()
    def CrashFromOmniThread(self):
        # PROTECTED REGION ID(TangoTest.CrashFromOmniThread) ENABLED START #
        pass
        # PROTECTED REGION END #    //  TangoTest.CrashFromOmniThread

    @command(dtype_in='bool', 
    doc_in="Any boolean value", 
    dtype_out='bool', 
    doc_out="Echo of the argin value"
    polling_period=3000,
    )
    @DebugIt()
    def DevBoolean(self, argin):
        # PROTECTED REGION ID(TangoTest.DevBoolean) ENABLED START #
        return False
        # PROTECTED REGION END #    //  TangoTest.DevBoolean

    @command(dtype_in='double', 
    doc_in="Any DevDouble value", 
    dtype_out='double', 
    doc_out="Echo of the argin value"
    display_level=DispLevel.EXPERT,
    polling_period=3000,
    )
    @DebugIt()
    def DevDouble(self, argin):
        # PROTECTED REGION ID(TangoTest.DevDouble) ENABLED START #
        return 0.0
        # PROTECTED REGION END #    //  TangoTest.DevDouble

**Comment by vxgmichel** [comment]
Yep, but you missed a comma at the end of the `doc_out` lines:

> doc_out="Echo of the argin value"
display_level=DispLevel.EXPERT,

**Comment by NexeyaSGara** [comment]
Ok, I can put a coma in every case, even if there is nothing after right ?

**Comment by vxgmichel** [comment]
@NexeyaSGara yes that's fine

**Comment by NexeyaSGara** [comment]
Done, will be available in the next Pogo release
