### ISSUE TITLE
could you add this platform 'gnukfreebsd9'

### ISSUE THREAD

**Issue by picca** [tango-cs/pytango#51]
This is in order to build pytango on the kfreebsd port of debian.

>>> sys.platform
'gnukfreebsd9'

Usually for each new version of the kfreebsd kenel the number is increased, so maybe the best solution is to check only for gnukfreebsd.

thanks

**Comment by picca** [comment]
another platform is hurd.

>>> import sys
>>> sys.platform
'gnu0'

**Comment by vxgmichel** [comment]
For the record, here's the list of the tests we perform in `setup.py`:
```
posix = 'posix' in os.name
linux = 'linux' in sys.platform
dist_name = platform.linux_distribution()[0].lower()
debian = 'debian' in dist_name or 'ubuntu' in dist_name or 'mint' in dist_name
gentoo ='gentoo' in dist_name
redhat = 'fedora' in dist_name or 'centos' in dist_name
```
I suggest we replace `linux` with `posix` and use `platform.platform()` instead of `platform.linux_distribution()` since it will be deprecated in python 3.6:
```
posix = 'posix' in os.name
windows = 'nt' in os.name
platform_name = platform.platform().lower()
debian = any(x in platform_name for x in ['debian', 'ubuntu', 'mint'])
redhat = any(x in platform_name for x in ['redhat', 'fedora', 'centos'])
gentoo = any(x in platform_name for x in ['gentoo'])
``` 
What do you think @tiagocoutinho ?

**Comment by tiagocoutinho** [comment]
Ok with me. Thanks for the cleanup.

@picca, can you make a PR or would you prefer one of us adds the _gnukfreebsd_ and _gnu0_ support?

**Comment by picca** [comment]
Hello, no thanks I prefer to let @vxgmichel do the job. I am more confident that he would do the right thing ;)
